language: node_js
      
node_js:
  - "6"
  - "7"
  - "8"

script:
  - npm i && npm run test

before_script:
  # install nats
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.6/gnatsd-v0.9.6-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v0.9.6-linux-amd64 gnatsd