/** Declaration file generated by dts-gen */

export function add_member(port: any, route_port: any, cluster_port: any, opt_flags: any, done: any): any;

export function add_member_with_delay(ports: any, route_port: any, delay: any, opt_flags: any, done: any): any;

export function start_cluster(ports: any, route_port: any, opt_flags: any, done: any): any;

export function start_server(port: any, opt_flags: any, done: any): any;

export function stop_cluster(servers: any): void;

export function stop_server(server: any): void;
